name: stripe_api_sdk
description: Unofficial Stripe API SDK
version: 1.0.2+3
homepage: https://raw-ware-official-website.web.app/
repository: https://github.com/LiveUser/stripe_api_sdk

environment:
  sdk: '>=2.17.0-266.7.beta <3.0.0'
dependencies:
  sexy_api_client: ^0.0.6+6
  raw_encoder: ^1.0.1+2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
